# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

clone_depth: 1

environment:
  matrix:
    - nodejs_version: "5.1"

platform:
  - x64

cache:
  - bower_components -> bower.json
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'
  - '%APPDATA%\Roaming\bower'

branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # Let's try to get things working
  # Install Node 5 ---------------------------------------------------------
  - ps: Install-Product node 5.1
  # Typical npm stuff ------------------------------------------------------
  - md C:\nc
  - npm version
  - npm config set cache C:\nc
  # Installation, globals --------------------------------------------------
  - npm install -g --no-color --no-progress bower 
  # Installation, deps -----------------------------------------------------
  - npm install --no-optional --no-color --no-progress --ignore-scripts
  - bower install

# We don't actually run the full test suite (that's a TODO left, but we do
# attempt to build).
test_script:
  - node ./node_modules/ember-cli/bin/ember build
  
# Set build version format here instead of in the admin panel.
build: off
version: "{build}"